name: resume_flutter_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1 

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.png"  
  adaptive_icon_foreground: "images/logo.png" 
  adaptive_icon_background: "images/logo.png"  

flutter:
  uses-material-design: true

  assets:
    - images/
    - lib/assets/ziyaret_ashura.txt
